/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Background = string | LinearGradient;
export type DimensionValue = number | null;
export type Content = Code | CommandLineContent[];
export type HighlightLine = [number, string] | [number, number, string];

export interface SnapshotConfig {
  background: Background;
  code_config: CodeConfig;
  /**
   * The code to be displayed in the snapshot
   */
  command_output_config: CommandOutputConfig;
  content: Content;
  /**
   * Load fonts from the fonts_folders to render the code, CodeSnap use fonts which you have installed on your system by default, but you can still provide `fonts_folders` to tell CodeSnap to load extra fonts from the folder.
   *
   * This config is useful when you want to develop a tool based on CodeSnap, you can package some fonts with your tool and publish, so that users can use these fonts without installing them manually on their system.
   */
  fonts_folders: string[];
  line_number_color: string;
  /**
   * CodeSnap default generate triple size snapshot image, you can use this config to change the scale factor.
   */
  scale_factor?: number;
  /**
   * CodeSnap use Syntect as the syntax highlighting engine, you can provide a custom theme for code highlighting and background. The theme is load from the `themes_folders`(if not provided, CodeSnap load the default themes), you can use the theme name to specify the theme you want to use.
   *
   * See `themes_folders` config for more detail.
   */
  theme: string;
  /**
   * CodeSnap use Syntect as the syntax highlighting engine, you can provide a custom theme for the snapshot. If the `themes_folders` is provided, CodeSnap will load the theme from the folder, otherwise, CodeSnap will load the default themes.
   *
   * Visit https://github.com/trishume/syntect for more detail
   */
  themes_folders: string[];
  title?: string | null;
  watermark?: Watermark | null;
  window: Window;
  [k: string]: unknown;
}
export interface LinearGradient {
  end: PointFor_DimensionValue;
  start: PointFor_DimensionValue;
  stops: LinearGradientStop[];
  [k: string]: unknown;
}
export interface PointFor_DimensionValue {
  x: DimensionValue;
  y: DimensionValue;
  [k: string]: unknown;
}
export interface LinearGradientStop {
  color: string;
  position: number;
  [k: string]: unknown;
}
export interface CodeConfig {
  /**
   * Breadcrumbs is a useful and unique feature of CodeSnap, it can help users to understand the code location in the project. If the `has_breadcrumbs` is true, CodeSnap will display the `file_path` on top of the code.
   *
   * The code snapshot is different from normal screenshots, it should provide more information about the code, such as the file path, the line number and highlight code line, these information can help users to understand the code better.
   */
  breadcrumbs?: Breadcrumbs;
  font_family: string;
  [k: string]: unknown;
}
export interface Breadcrumbs {
  color: string;
  enable: boolean;
  font_family: string;
  separator: string;
  [k: string]: unknown;
}
export interface CommandOutputConfig {
  command_color: string;
  font_family: string;
  prompt: string;
  prompt_color: string;
  string_arg_color: string;
  [k: string]: unknown;
}
export interface Code {
  content: string;
  file_path?: string | null;
  highlight_lines?: HighlightLine[];
  /**
   * The `language` will be used to determine the syntax highlighting to use for generating the snapshot.
   */
  language?: string | null;
  start_line_number?: number | null;
  [k: string]: unknown;
}
export interface CommandLineContent {
  content: string;
  full_command: string;
  [k: string]: unknown;
}
/**
 * Draw a watermark below the code, you can use this to add a logo or any other text The watermark is designed as a place for users to provide personalize label
 */
export interface Watermark {
  color: string;
  content: string;
  font_family: string;
  [k: string]: unknown;
}
export interface Window {
  border: Border;
  mac_window_bar: boolean;
  margin: Margin;
  shadow: Shadow;
  title_config: TitleConfig;
  [k: string]: unknown;
}
export interface Border {
  color: string;
  width: number;
  [k: string]: unknown;
}
export interface Margin {
  x: number;
  y: number;
  [k: string]: unknown;
}
export interface Shadow {
  color: string;
  radius: number;
  [k: string]: unknown;
}
export interface TitleConfig {
  color: string;
  font_family: string;
  [k: string]: unknown;
}
